In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('/content/predictive_maintenance.csv')

In [ ]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure

In [ ]:
print(df.describe().T)

                           count        mean          std     min      25%  \
UDI                      10000.0  5000.50000  2886.895680     1.0  2500.75
Air temperature [K]      10000.0   300.00493     2.000259   295.3   298.30
Process temperature [K]  10000.0   310.00556     1.483734   305.7   308.80
Rotational speed [rpm]   10000.0  1538.77610   179.284096  1168.0  1423.00
Torque [Nm]              10000.0    39.98691     9.968934     3.8    33.20
Tool wear [min]          10000.0   107.95100    63.654147     0.0    53.00
Target                   10000.0     0.03480     0.183282     0.0     0.00

                            50%      75%      max
UDI                      5000.5  7500.25  10000.0
Air temperature [K]       300.1   301.50    304.5
Process temperature [K]   310.1   311.10    313.8
Rotational speed [rpm]   1503.0  1612.00   2886.0
Torque [Nm]                40.1    46.80     76.6
Tool wear [min]           108.0   162.00    253.0
Target                      0.0     0.00      1.0

In [ ]:
print(df.info())
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Target                   10000 non-null  int64
 9   Failure Type             10000 non-null  object
dtypes: float64(3), int64(4), object(3)
memory usage: 781.4+ KB
None

(10000, 10)

In [ ]:
df.nunique()

UDI                        10000
Product ID                 10000
Type                           3
Air temperature [K]           93
Process temperature [K]       82
Rotational speed [rpm]       941
Torque [Nm]                  577
Tool wear [min]              246
Target                         2
Failure Type                   6
dtype: int64

In [ ]:
df.notnull()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
9995,True,True,True,True,True,True,True,True,True,True
9996,True,True,True,True,True,True,True,True,True,True
9997,True,True,True,True,True,True,True,True,True,True
9998,True,True,True,True,True,True,True,True,True,True
9999,True,True,True,True,True,True,True,True,True,True

In [ ]:
for col in df[['Type','Target','Failure Type']]:
    print(df[col].value_counts())

Type
L    6000
M    2997
H    1003
Name: count, dtype: int64
Target
0    9652
1     348
Name: count, dtype: int64
Failure Type
No Failure                  9652
Heat Dissipation Failure     112
Power Failure                 95
Overstrain Failure            78
Tool Wear Failure             45
Random Failures               18
Name: count, dtype: int64

In [ ]:
df[df['Target']==1]

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
50,51,L47230,L,298.9,309.1,2861,4.6,143,1,Power Failure
69,70,L47249,L,298.9,309.0,1410,65.7,191,1,Power Failure
77,78,L47257,L,298.8,308.9,1455,41.3,208,1,Tool Wear Failure
160,161,L47340,L,298.4,308.2,1282,60.7,216,1,Overstrain Failure
161,162,L47341,L,298.3,308.1,1412,52.3,218,1,Overstrain Failure
...,...,...,...,...,...,...,...,...,...,...
9758,9759,L56938,L,298.6,309.8,2271,16.2,218,1,Tool Wear Failure
9764,9765,L56944,L,298.5,309.5,1294,66.7,12,1,Power Failure
9822,9823,L57002,L,298.5,309.4,1360,60.9,187,1,Overstrain Failure
9830,9831,L57010,L,298.3,309.3,1337,56.1,206,1,Overstrain Failure
9974,9975,L57154,L,298.6,308.2,1361,68.2,172,1,Power Failure

In [ ]:
X = df.iloc[:,2:8]# takes the colomn Type and Target
y = df.iloc[:,-1] # takes the colomn Faliture_type

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=21) #splits the data and allocate it in 80% for training and 20% for testing
y_train.shape

(8000,)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
# conversin of values of Type in 'int' Data type
oe = OrdinalEncoder(categories=[['L','M','H']])
oe.fit(X_train[['Type']])
X_train['Type']=oe.transform(X_train[['Type']]).astype(int)
X_test['Type']=oe.transform(X_test[['Type']]).astype(int)

In [ ]:
X_train.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min]
5504,0,302.8,312.2,1458,51.0,42
5307,0,304.0,313.3,1530,34.8,211
1684,0,297.8,307.3,1438,44.5,3
2441,0,299.1,308.5,1676,31.0,69
0,1,298.1,308.6,1551,42.8,0

In [ ]:
for col in df[['Type','Target','Failure Type']]:
    print(df[col].value_counts())

Type
L    6000
M    2997
H    1003
Name: count, dtype: int64
Target
0    9652
1     348
Name: count, dtype: int64
Failure Type
No Failure                  9652
Heat Dissipation Failure     112
Power Failure                 95
Overstrain Failure            78
Tool Wear Failure             45
Random Failures               18
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
#encoding the categorical target variable 'Failure Type' into numerical values
categories=['No Failure','Heat Dissipation Failure','Power Failure','Overstrain Failure','Tool Wear Failure','Random Failures']
custom_encoder={cat: i for i, cat in enumerate(categories)}
y_train_encoded=[custom_encoder.get(cat,len(categories))for cat in y_train]
y_test_encoded=[custom_encoder.get(cat,len(categories))for cat in y_test]
le=LabelEncoder()
le.fit(list(custom_encoder.values()))
y_train=le.transform(y_train_encoded)
y_test=le.transform(y_test_encoded)

In [ ]:
#Logistic Regression model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
clf=LogisticRegression(solver='lbfgs', max_iter=10000)
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
log_train=round(clf.score(X_train, y_train) * 100, 2)
log_accuracy=round(accuracy_score(y_pred, y_test)* 100, 2)
print("Training Accuracy :",log_train,"%")
print("Model Accuracy Score", log_accuracy, "%")
print("Classification_Report: \n",classification_report(y_test,y_pred))

Training Accuracy : 98.15 %
Model Accuracy Score 98.05 %
Classification_Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      1921
           1       1.00      0.38      0.55        32
           2       0.90      0.95      0.92        19
           3       0.93      0.81      0.87        16
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00         3

    accuracy                           0.98      2000
   macro avg       0.64      0.52      0.55      2000
weighted avg       0.97      0.98      0.98      2000

In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
decision=DecisionTreeClassifier()
decision.fit(X_train, y_train)
y_pred_dec=decision.predict(X_test)
decision_train=round(decision.score(X_train, y_train)*100, 2)
decision_accuracy=round(accuracy_score(y_pred_dec, y_test)*100, 2)
print("Training Accuracy :", decision_train, "%")
print("Model Accuracy Score", decision_accuracy, "%")
print("Classification_Report: \n", classification_report(y_test,y_pred_dec))

Training Accuracy : 100.0 %
Model Accuracy Score 97.7 %
Classification_Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1921
           1       0.82      0.84      0.83        32
           2       0.73      0.84      0.78        19
           3       0.92      0.69      0.79        16
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00         3

    accuracy                           0.98      2000
   macro avg       0.57      0.56      0.56      2000
weighted avg       0.98      0.98      0.98      2000

In [ ]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
random_forest=RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
y_pred_rf=random_forest.predict(X_test)
random_forest.score(X_train, y_train)
random_forest_train=round(random_forest.score(X_train, y_train)*100, 2)
random_forest_accuracy=round(accuracy_score(y_pred_rf, y_test)*100, 2)
print("Training Accuracy ",random_forest_train, "%")
print("Model Accuracy Score", random_forest_accuracy, "%")
print("Classification_Report: \n", classification_report(y_test,y_pred_rf))

Training Accuracy  100.0 %
Model Accuracy Score 98.5 %
Classification_Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1921
           1       1.00      0.62      0.77        32
           2       1.00      1.00      1.00        19
           3       0.92      0.69      0.79        16
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00         3

    accuracy                           0.98      2000
   macro avg       0.65      0.55      0.59      2000
weighted avg       0.98      0.98      0.98      2000

In [ ]:
#Support Vector Machines
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)
y_pred_svc=svc.predict(X_test)
svc_train=round(svc.score(X_train, y_train)*100, 2)
svc_accuracy=round(accuracy_score(y_pred_svc, y_test)*100, 2)
print("Training Accuracy ",svc_train, "%")
print("Model Accuracy Score", svc_accuracy, "%")
print("Classification_Report: \n",classification_report(y_test,y_pred_svc))

Training Accuracy  96.67 %
Model Accuracy Score 96.15 %
Classification_Report:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98      1921
           1       0.00      0.00      0.00        32
           2       1.00      0.11      0.19        19
           3       0.00      0.00      0.00        16
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00         3

    accuracy                           0.96      2000
   macro avg       0.33      0.18      0.20      2000
weighted avg       0.93      0.96      0.94      2000